name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag guxvega/front-end:dev
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the docker image to Docker hub
      run: docker push guxvega/front-end:dev
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: mainautomationcr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Tag Image for ACR
      run: docker tag guxvega/front-end:dev mainautomationcr.azurecr.io/front-end:dev
    - name: Push the docker image to Azure Container Registry
      run: docker push mainautomationcr.azurecr.io/front-end:dev
